[package]
name = "bevy_ecs_tilemap_tileset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
bevy_ecs_tilemap = "0.4.0"
bevy_tile_atlas = "0.1.1"
ron = "0.7.0"
serde = "1.0.130"
rand = "0.8"

[[example]]
name = "clickable"
path = "examples/clickable.rs"