[package]
name = "bevy_ecs_tilemap_tileset"
version = "0.1.0"
edition = "2021"
authors = ["Gino Valente <gino.valente.code@gmail.com>"]
description = "An extension to the bevy_ecs_tilemap, allowing for configurable tilesets, auto tiling, and more"
repository = "https://github.com/MrGVSV/bevy_ecs_tilemap_tileset"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "tileset", "auto", "variant", "tile"]
categories = ["game-development"]
readme = "README.md"
exclude = ["assets/**/*", ".github/**/*"]

[badges]
maintenance = { status = "experimental" }

[dependencies]
bevy = "0.5"
bevy_ecs_tilemap = "0.4.0"
bevy_tile_atlas = "0.1.1"
ron = "0.7.0"
serde = "1.0.130"
rand = "0.8"

[[example]]
name = "clickable"
path = "examples/clickable.rs"